# Generated by Django 3.2.16 on 2023-08-14 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиента должно быть больше 1'), django.core.validators.MaxValueValidator(5000, message='Количество ингредиента должно быть меньше 5000')], verbose_name='Количество ингредиента'),
        ),
    ]
