# Generated by Django 3.2.16 on 2023-08-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_shoppingcart_unique_shopping_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингридиенты', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_ingredients_recipe',
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredienttorecipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
